### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by xANoyU** [UnDeadlyDev/UTitleAuth#8]
```
[20:21:46] [User Authenticator #1/INFO]: UUID of player EpsilonRs is xxx-xxx-xxx-xxx
[20:21:46] [Server thread/INFO]: EpsilonRs[/xxx.xxx.xxx.xxx:xxx] logged in with entity id 1 at ([world]23.5, 82.0, -10.4)
[20:21:46] [Craft Scheduler Thread - 2/INFO]: [AuthMe] EpsilonRs logged in xxx.xxx.xxx.xxx
[20:21:46] [Server thread/ERROR]: Could not pass event LoginEvent to UTitleAuth v7.9.7
java.lang.NoSuchMethodError: net.md_5.bungee.api.ChatColor.of(Ljava/lang/String;)Lnet/md_5/bungee/api/ChatColor;
	at com.undeadlydev.UTitleAuth.utils.HexUtils.translateHex(HexUtils.java:257) ~[?:?]
	at com.undeadlydev.UTitleAuth.utils.HexUtils.parseHex(HexUtils.java:222) ~[?:?]
	at com.undeadlydev.UTitleAuth.utils.HexUtils.colorify(HexUtils.java:74) ~[?:?]
	at com.undeadlydev.UTitleAuth.utils.ChatUtils.colorCodes(ChatUtils.java:8) ~[?:?]
	at com.undeadlydev.UTitleAuth.managers.FileManager.get(FileManager.java:95) ~[?:?]
	at com.undeadlydev.UTitleAuth.managers.TitlesManager.SendTitleOnLogin(TitlesManager.java:67) ~[?:?]
	at com.undeadlydev.UTitleAuth.listeners.LoginListener.OnLoginPlayer(LoginListener.java:37) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor156.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70) ~[patched_1.12.2.jar:git-Paper-1620]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched_1.12.2.jar:git-Paper-1620]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.12.2.jar:git-Paper-1620]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:513) ~[patched_1.12.2.jar:git-Paper-1620]
	at fr.xephi.authme.service.BukkitService.callEvent(BukkitService.java:315) ~[?:?]
	at fr.xephi.authme.process.login.ProcessSyncPlayerLogin.processPlayerLogin(ProcessSyncPlayerLogin.java:119) ~[?:?]
	at fr.xephi.authme.process.SyncProcessManager.lambda$processSyncPlayerLogin$3(SyncProcessManager.java:52) ~[?:?]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:64) ~[patched_1.12.2.jar:git-Paper-1620]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:423) ~[patched_1.12.2.jar:git-Paper-1620]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:840) ~[patched_1.12.2.jar:git-Paper-1620]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423) ~[patched_1.12.2.jar:git-Paper-1620]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:774) ~[patched_1.12.2.jar:git-Paper-1620]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:666) ~[patched_1.12.2.jar:git-Paper-1620]
	at java.lang.Thread.run(Thread.java:855) [?:?]
```

**Comment by xANoyU** [comment]
my bad, i use RGB code xD
